### ISSUE TITLE
Question regarding landmark geometry

### ISSUE THREAD

**Issue by jeew00** [zhangzjn/APB2Face#1]
First of all, appreciate your amazing work. I have a question about how you extract landmark geometry. I tried to extract it using the [faceplusplus' Face Detection API](https://console.faceplusplus.com/documents/5679127), and it returned x and y coordinate of 106-point landmarks, but in the AnnVI dataset, landmark geometry is 212-dimensional vector. So my question is that how do you compute the landmark geometry feature from the output provided by the API? Thank in advance!

**Comment by zhangzjn** [comment]
The geometric information of the face refers to the landmark itself. When getting the landmark from the Face++ API, you can simply flatten it to a 212-D vector (x_0, y_0, ..., x_{105}, y_{105}). You may find more details of the dataset in the released AnnVI.

**Comment by zhangzjn** [comment]
@jeewling 
The geometric information of the face refers to the landmark itself. When getting the landmark from the Face++ API, you can simply flatten it to a 212-D vector (x_0, y_0, ..., x_{105}, y_{105}). You may find more details of the dataset in the released AnnVI.

**Comment by jeew00** [comment]
Got it. Thanks for such a fast reply.

**Comment by jeew00** [comment]
I have one more question to ask. Can you elaborate more on how you
preprocess audio to get MFCC features of shape 64x60 per frame? Thank you
very much.

**Comment by zhangzjn** [comment]
@jeewling 
You can first use 'librosa.feature.mfcc' to extract the mfcc feature with params 'n_mfcc=20, n_fft=2048, hop_length=512' and calculate the first-order as well as the second-order of the mfcc feature. Then use window size 64 to get the audio feature of one frame.

**Comment by jeew00** [comment]
Since there are a lot of frame, how do you map each audio frame to the
corresponding video frame? Did you use sliding window on MFCC features or
something else?

**Comment by zhangzjn** [comment]
@jeewling 
frame_count / video_rate = signal_count / audio_rate, then you can align the frame with corresponding audio pointcut and sample MFCC feature.

**Comment by jeew00** [comment]
I am using signal_count / frame_count to find audio samples per frame and
then use it to chunk the full audio sample into pieces and then using those
pieces to extract MFCC features. Is that the correct way to do it? If so
when I use hop_length=512, I get only 2 windows of MFCC feature.

**Comment by zhangzjn** [comment]
@jeewling 
I first extract the MFCC feature of the whole audio and then sample MFCC features.

**Comment by jeew00** [comment]
After you sample MFCC feature of the whole audio, how did you chunk it?

**Comment by zhangzjn** [comment]
mfcc_f = mfcc_fs[:, c_cnt - win_size // 2: c_cnt + win_size // 2]
